api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            enabled: false

    swagger:
      api_keys:
        apiKey:
          name: Authorization
          type: header